In [1]:
from sklearn.cluster import AffinityPropagation as AP
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from cluster.dataset import load_time_series

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import colors
import seaborn as sns
%matplotlib inline
from sklearn.cluster import DBSCAN, KMeans, MiniBatchKMeans
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import matplotlib.gridspec as gridspec

In [2]:
data = load_time_series(1)
data = data.groupby(data.datetime)["pwr"].sum()
data.index = pd.to_datetime(data.index)
time_index = np.unique(data.index.date).astype(str)

In [16]:
from chinese_calendar import get_holidays, is_holiday, holidays, get_holiday_detail
from datetime import datetime as dt

In [12]:
dates = pd.date_range(time_index[0], time_index[-1])

In [22]:
get_holiday_detail(dates[3])

(True, None)

In [36]:
t = pd.DataFrame({"date": dates, "is_holiday": dates.map(lambda x: int(is_holiday(x))), 
              "weekday": dates.weekday, "holiday_details": dates.map(lambda x:get_holiday_detail(x)[-1]
                                                                     if get_holiday_detail(x)[-1] else '')})

In [48]:
ap = AP().fit(data.values.reshape(-1, 48))
kmeans = KMeans().fit(data.values.reshape(-1, 48))
mkmeans = MiniBatchKMeans().fit(data.values.reshape(-1, 48))

In [50]:
t["ap_label"] = ap.labels_
t["kmeans_label"] = kmeans.labels_
t["mbkmeans_label"] = mkmeans.labels_

In [51]:
t

date holiday_details  is_holiday  weekday  ap_label  kmeans_label  \
0   2017-06-01                           0        3        12             7   
1   2017-06-02                           0        4         6             3   
2   2017-06-03                           1        5        13             7   
3   2017-06-04                           1        6        13             7   
4   2017-06-05                           0        0         6             7   
5   2017-06-06                           0        1         4             3   
6   2017-06-07                           0        2         5             3   
7   2017-06-08                           0        3         4             3   
8   2017-06-09                           0        4         5             3   
9   2017-06-10                           1        5        13             7   
10  2017-06-11                           1        6        13             7   
11  2017-06-12                           0        0         5             3   
12  2017-06-13                           0        1         6             7   
13  2017-06-14                           0        2         6             7   
14  2017-06-15                           0        3         6             7   
15  2017-06-16                           0        4         6             3   
16  2017-06-17                           1        5        13             7   
17  2017-06-18                           1        6        13             7   
18  2017-06-19                           0        0         4             3   
19  2017-06-20                           0        1         4             3   
20  2017-06-21                           0        2         5             3   
21  2017-06-22                           0        3         5             3   
22  2017-06-23                           0        4         4             3   
23  2017-06-24                           1        5         0             7   
24  2017-06-25                           1        6        13             7   
25  2017-06-26                           0        0         6             3   
26  2017-06-27                           0        1         4             3   
27  2017-06-28                           0        2         4             3   
28  2017-06-29                           0        3         5             3   
29  2017-06-30                           0        4         3             1   
..         ...             ...         ...      ...       ...           ...   
396 2018-07-02                           0        0        15             1   
397 2018-07-03                           0        1        16             2   
398 2018-07-04                           0        2        16             2   
399 2018-07-05                           0        3        16             2   
400 2018-07-06                           0        4        16             2   
401 2018-07-07                           1        5         5             3   
402 2018-07-08                           1        6        17             6   
403 2018-07-09                           0        0        14             2   
404 2018-07-10                           0        1        15             1   
405 2018-07-11                           0        2        14             2   
406 2018-07-12                           0        3        14             3   
407 2018-07-13                           0        4        15             2   
408 2018-07-14                           1        5        17             6   
409 2018-07-15                           1        6        17             6   
410 2018-07-16                           0        0        16             2   
411 2018-07-17                           0        1        15             1   
412 2018-07-18                           0        2        16             2   
413 2018-07-19                           0        3        15             1   
414 2018-07-20                           0        4        1

In [52]:
t.mbkmeans_label.unique()

array([1, 5, 3, 4, 6, 2, 0, 7])

In [80]:
from sklearn.metrics.pairwise import euclidean_distances, cosine_distances

In [81]:
cosine_distances(np.zeros([10,5]),np.zeros([10,5]))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [82]:
cosine_distances(np.ones([10,5]),np.ones([10,5]))

array([[  1.11022302e-16,   1.11022302e-16,   1.11022302e-16,
          1.11022302e-16,   1.11022302e-16,   1.11022302e-16,
          1.11022302e-16,   1.11022302e-16,   1.11022302e-16,
          1.11022302e-16],
       [  1.11022302e-16,   1.11022302e-16,   1.11022302e-16,
          1.11022302e-16,   1.11022302e-16,   1.11022302e-16,
          1.11022302e-16,   1.11022302e-16,   1.11022302e-16,
          1.11022302e-16],
       [  1.11022302e-16,   1.11022302e-16,   1.11022302e-16,
          1.11022302e-16,   1.11022302e-16,   1.11022302e-16,
          1.11022302e-16,   1.11022302e-16,   1.11022302e-16,
          1.11022302e-16],
       [  1.11022302e-16,   1.11022302e-16,   1.11022302e-16,
          1.11022302e-16,   1.11022302e-16,   1.11022302e-16,
          1.11022302e-16,   1.11022302e-16,   1.11022302e-16,
          1.11022302e-16],
       [  1.11022302e-16,   1.11022302e-16,   1.11022302e-16,
          1.11022302e-16,   1.11022302e-16,   1.11022302e-16,
          1.11022302e-16